---
- hosts: master
  become: true
  vars:
    node_ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
    node_subnet: 10.181.0.0/16
    user: ubuntu

  tasks:
  - name: Run the equivalent of "apt-get update" as a separate step
    apt:
      update_cache: yes

  - name: Install packages that allow apt to be used over HTTPS
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
 
  - name: Add an apt signing key for Docker
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
 
  - name: Add apt repository for stable version
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present
 
  - name: Install docker and its dependecies
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io
    notify:
      - docker status
 
  - name: "Add {{ user }} user to docker group"
    user:
      name: "{{ user }}"
      group: docker
 
  - name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none
 
  - name: Disable swap
    command: swapoff -a
    when: ansible_swaptotal_mb > 0
 
  - name: Add an apt signing key for Kubernetes
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present
 
  - name: Adding apt repository for Kubernetes
    apt_repository:
      repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: kubernetes.list
 
  - name: Install Kubernetes binaries
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
        - kubelet 
        - kubeadm 
        - kubectl
 
  - name: Restart kubelet
    service:
      name: kubelet
      daemon_reload: yes
      state: restarted
 #https://stackoverflow.com/questions/52119985/kubeadm-init-shows-kubelet-isnt-running-or-healthy issue with Ubuntu 18.04
  - name: Initialize the Kubernetes cluster using kubeadm
    command: kubeadm init --apiserver-advertise-address={{ node_ip }} --apiserver-cert-extra-sans={{ node_ip }}  --node-name k8s-master --pod-network-cidr={{ node_subnet}}
    become: true
    
  - name: "Setup kubeconfig for {{ user }} user"
    command: "{{ item }}"
    with_items:
    - "mkdir -p /home/{{ user }}/.kube"
    - "cp -i /etc/kubernetes/admin.conf /home/{{ user }}/.kube/config"
    - "chown {{ user }}:{{ user }} /home/{{ user }}/.kube/config"

  - name: Install calico pod network
    command: kubectl apply -f https://docs.projectcalico.org/v3.9/manifests/calico.yaml
    become: true
    
  - name: Generate join command
    command: kubeadm token create --print-join-command
    register: join_command

  - name: Copy join command to local file
    become: false
    local_action: 
      module: copy 
      content: "{{ join_command.stdout_lines[0] }}" 
      dest: "./join-command"

  handlers:
    - name: docker status
      service: 
        name: docker 
        state: started